### ISSUE TITLE
Footer formatting

### ISSUE THREAD

**Issue by octocatblain** [Nmcleon/recipes#3]
- [x] Social buttons should be rounded
- [x] Footer margin and text padding 
- [x] Adjust font weight of text

**Comment by cjstyles6** [comment]
@octocatblain assign me to this issue

**Comment by octocatblain** [comment]
> @octocatblain assign me to this issue

@cjstyles6 I am currently working on this one :(

**Comment by cjstyles6** [comment]
Oh ok no prob, if you need help with any other issue. I'd be glad to help
