### ISSUE TITLE
Format sections in Home page

### ISSUE THREAD

**Issue by octocatblain** [Nmcleon/recipes#7]
- [x] Add 2 more sections below the hero image
- [x] Update recipe cards to 2 in a row
- [x] Edit footer links

**Comment by Nmcleon** [comment]
I'll update links once the Icons are updated 
I'll check the index page 😶‍🌫️

**Comment by octocatblain** [comment]
> I'll update links once the Icons are updated I'll check the index page 😶‍🌫️

- did you intent to have the navigation transparent on scroll?
![image](https://github.com/Nmcleon/recipes/assets/62080362/56e24ef6-8850-44a9-9eb7-b168882eeef0)
