### ISSUE TITLE
Source recipe images

### ISSUE THREAD

**Issue by octocatblain** [Nmcleon/recipes#8]
- [x] #10
- [x] Home page images
- [x] Website logo @Nmcleon

**Comment by Nmcleon** [comment]
-  fa2ee5d This contains images for the whole website
- Logo will proberbly be uploaded tomorrow

**Comment by octocatblain** [comment]
@Nmcleon Yeah I noticed that later

**Comment by Nmcleon** [comment]
[506ba2d](https://github.com/Nmcleon/recipes/commit/506ba2d2e77d42aed95e41c662657f7c94963c7f) Done
